title: "Julio Barros"
description: "Physicist â€” data science, material science, modeling, and visualization"
theme: jekyll-theme-minimal
logo: /profile.jpeg

# Social links (optional for header)
github: https://github.com/juliobarros-BR
linkedin: https://www.linkedin.com/in/julio-o-amando-de-barros-a80861129/
google_scholar: https://scholar.google.com/citations?user=0siqWoIAAAAJ&hl=en&oi=ao

# Optional extras

