title: "JÃºlio Amando de Barros"
description: "Physicist with experience in material science, modeling, automation, data science, and data visualization"
theme: jekyll-theme-minimal
logo: /profile.jpeg

show_downloads: false
include:
  - assets

# === Social links ===
github: https://github.com/juliobarros-BR
linkedin: https://www.linkedin.com/in/julio-o-amando-de-barros-a80861129/
google_scholar: https://scholar.google.com/citations?user=0siqWoIAAAAJ&hl=en&oi=ao

# === Top navigation menu ===
header_pages:
  - index.md
  - research-projects.md
  - other-projects.md
  - personal.md


# === Contact links (shown under picture) ===
contact:
  - name: "ğŸ“„ Download CV"
    url: "cv.pdf"
  - name: "ğŸ’¼ GitHub"
    url: "https://github.com/juliobarros-BR"
  - name: "ğŸ”— LinkedIn"
    url: "https://www.linkedin.com/in/julio-o-amando-de-barros-a80861129/"
  - name: "ğŸ“ Google Scholar"
    url: "https://scholar.google.com/citations?user=0siqWoIAAAAJ&hl=en&oi=ao"
  - name: "âœ‰ï¸ julioortizbarros@gmail.com"
    url: "mailto:julioortizbarros@gmail.com"
